[project]
name = "research2026"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "google-genai>=2.7.0",
    "openai>=2.38.0",
    "openrouter>=0.9.1",
    "python-dotenv>=1.2.2",
    "requests>=2.34.2",
    "tqdm>=4.67.3",
]

[dependency-groups]
dev = [
    "ruff>=0.15.15",
]
