[project]
name = "research2026"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "accelerate>=1.13.0",
    "evaluate>=0.4.6",
    "matplotlib>=3.10.9",
    "openrouter>=0.9.2",
    "pandas>=3.0.3",
    "pydriller>=2.9",
    "python-dotenv>=1.2.2",
    "requests>=2.34.2",
    "tqdm>=4.67.3",
    "transformers>=5.9.0",
]

[tool.pytest.ini_options]
pythonpath = ["."]

[dependency-groups]
dev = [
    "pytest>=9.0.3",
    "ruff>=0.15.15",
]
